### ISSUE TITLE
报错：Component is not found in path "components/custom-tab-bar/index" (using by "pages/index/index")

### ISSUE THREAD

**Issue by tomorrowNicest** [ljybill/miniprogram-custom-bottom#1]
您好，按照文章提供的方法引入报错
Component is not found in path "components/custom-tab-bar/index" (using by "pages/index/index")
![1562054549007](https://user-images.githubusercontent.com/34731610/60495240-f9dc0a00-9ce2-11e9-873f-75c68eb53e90.jpg)

**Comment by ljybill** [comment]
您好，请检查路径是否正确，应该是路径问题

**Comment by tomorrowNicest** [comment]
> 您好，请检查路径是否正确，应该是路径问题

我引入的问题，但是这个组件自定义的跳转跳转不了，app.json没有配置的路径自定义的路径跳转我了，我是以接口获取数据setData形式写的

**Comment by ljybill** [comment]
可以提供下代码片段或者截图吗？方便帮您解决问题

**Comment by tomorrowNicest** [comment]
3349574910能加我qq吗，这里感觉不方便

**Comment by tomorrowNicest** [comment]
![1562219433593](https://user-images.githubusercontent.com/34731610/60642617-2323a400-9e63-11e9-8790-43a40869a11d.jpg)
![1562219610810](https://user-images.githubusercontent.com/34731610/60642625-2b7bdf00-9e63-11e9-8fcb-d7747ed16010.jpg)
我在ready方法请求了底部导航的数据，然后setData，但是如果我在app.json中把其中的一个底部导航配置删除后点击底部导航就不跳转了。打印的switchTab方法中的跳转路径是正确的

**Comment by ljybill** [comment]
程序的switchTab方法 只对 app.json 中 tabBar list里面定义的才有效果，改成NavigateTo可行
